version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moard-mysql
    environment:
      - MYSQL_DATABASE=moard
      - MYSQL_USER=moard
      - MYSQL_PASSWORD=moard1234
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: moard-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/moard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=moard
      - SPRING_DATASOURCE_PASSWORD=moard1234
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 